dist: trusty
sudo: required

services:
  - docker

before_install:

script:
  - docker build -t fluxcapacitor/package-ubuntu-14.04 -f package.ml/ubuntu/14.04/Dockerfile .
  - docker build -t fluxcapacitor/package-anaconda-4.1.11 -f package.ml/anaconda/4.1.11/Dockerfile .
  - docker build -t fluxcapacitor/package-java-1.8 -f package.ml/java/1.8/Dockerfile .
  - docker build -t fluxcapacitor/package-spark-2.0.1 -f package.ml/spark/2.0.1/Dockerfile .
  - docker build -t fluxcapacitor/package-kafka-0.8 -f package.ml/kafka/0.8/Dockerfile .
  - docker build -t fluxcapacitor/package-kafka-0.10 -f package.ml/kafka/0.10/Dockerfile .
  - docker build -t fluxcapacitor/package-presto-0.145 -f package.ml/presto/0.145/Dockerfile .
  - docker build -t fluxcapacitor/package-apache2 -f package.ml/apache2/Dockerfile .
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push USER/REPO;
    fi
