site_name: PipelineIO 
site_url: http://pipeline.io
site_author: PipelineIO 
repo_url: https://github.com/fluxcapacitor/pipeline/
pages:
    - Home: index.md
    - Getting Started: 
        - Community Edition: products/community_edition.md
        - Professional Edition: products/professional_edition.md
        #- Amazon AWS: professional/aws_marketplace.md
        #- Google GCP: professional/gcp_marketplace.md
    - Getting Started: getting_started/index.hd
    - Command Line Interface: cli/index.md
    - REST API: rest/index.md
    - Model Training: 
        - Supported Models: model_deployments/supported_models.md
        - Apps and Tools: model_training/apps_and_tools.md
        - Fault Tolerance: model_training/fault_tolerance.md
        - Scalability: model_training/scalability.md
        - Command Line Interface: commands/index.md
        - REST API: model_training/rest.md
        - Examples: model_training/examples.md
        - Fault Tolerance: model_training/fault_tolerance.md
        - Scalability: model_training/scalability.md
    - Model Deployments: 
        - Supported Runtimes: model_deployments/supported_runtimes.md
        - REST-based: model_deployments/rest.md
        - Workflow: model_deployments/workflow.md
        - Rollbacks: model_deployments/rollbacks.md
        - Fault Tolerance: model_deployments/fault_tolerance.md
        - Scalability: model_deployments/scalability.md
    - Experimentation:
        - A/B Testing: experiments/ab_testing.md
        - Multi-armed Bandits: experiments/multi_armed_bandit_testing.md
        - Canary Deployment: model_deployments/canary.md
        - Traffic Splitting: model_deployments/traffic_splitting.md
        - Traffic Shadowing: model_deployments/traffic_shadowing.md
    - Model Predictions:
        - REST-based: predictions/rest.md
        - Streaming: predictions/streaming.md
    - Hybrid Cloud and On-Premise:
        - Federated Clusters: hybrid_cluster/federated.md
        - Heterogeneous GPU and CPU: hybrid_cluster/heterogeneous_gpu_and_cpu.md
    - Visualizations and Dashboards:
        - Metrics: visualizations/metrics.md
# TODO:  GPU METRICS!!
        - Workflow: visualizations/workflow.md
    - Performance: performance/index.md
    - GPUs: gpu/index.md
    - TPUs: tpu/index.md
    - FPGAs: fpga/index.md 
    - Training and Workshops: training/index.md
    - Open Source and Meetups: open_source/index.md
    - Contributing: contributing/index.md
    - Legal:
        - 'Privacy': legal/privacy.md
        - 'Terms of Service': legal/terms.md
theme: material
extra:
  palette:
    primary: 'orange'
    accent: 'orange'
    extra:
  logo: 'img/pipelineio-logo-128x128.png'
  font:
    text: 'Roboto'
    code: 'Source Code Pro'
  social:
    - type: 'github'
      link: 'https://github.com/fluxcapacitor/pipeline'
    - type: 'meetup'
      link: 'https://www.meetup.com/Advanced-Spark-and-TensorFlow-Meetup/'
    - type: 'youtube'
      link: 'https://youtube.com/channel/UCvlZKtekcKkBUuz8f9dhobw'
    - type: 'slideshare'
      link: 'https://www.slideshare.net/cfregly'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/6609122/'
    - type: 'twitter'
      link: 'https://twitter.com/pipelineio'
      
markdown_extensions:
    - markdown_include.include:
        base_path: docs 
extra_css:
    - css/bootstrap_paper.min.css
    - css/style.css
copyright: Copyright &copy; 2017 PipelineIO Inc.
