site_name: PipelineIO 
site_url: http://pipeline.io
site_author: PipelineIO
site_description: End-to-End ML and AI Model Training and Deployment Platform with GPUs 
repo_url: https://github.com/fluxcapacitor/pipeline/
repo_name: fluxcapacitor/pipeline 
edit_uri: edit/master/docs/
docs_dir: docs
site_dir: site
#strict: true
google_analytics:
  - 'UA-78551725-1'
  - 'auto'
pages:
  - Home: index.md
  - Getting Started: getting_started/index.md
  - Install PipelineIO: install/index.md
  - Command Line Interface: cli/index.md
  - REST API: rest/index.md
  - Train Model: model_train/index.md 
  - Optimize Model: model_optimize/index.md
  - Deploy Model: model_deploy/index.md 
  - Experiment: model_experiment/index.md
#      - A/B Testing: model_experiment/ab_testing.md
#      - Multi-armed Bandit Testing: model_experiment/multi_armed_bandit_testing.md
#  - Hybrid Cloud and On-Premise: cluster/index.md
#      - Federated Clusters: hybrid_cluster/federated.md
#      - Heterogeneous GPU and CPU: hybrid_cluster/heterogeneous_gpu_and_cpu.md
  - Monitor Model: model_monitor/index.md
  - Streaming: streaming/index.md
  - GPUs: gpu/index.md
  - Open Source: open_source/index.md
  - Contribute to PipelineIO: contribute/index.md
  - Community Events: community/index.md
  - Videos and Presentations: media/index.md
  - Training and Workshops: pio_training/index.md
#  - Datasets and Sources: data/index.md
  - Privacy and Terms: legal/index.md
theme: material
site_favicon: 'img/favicon.png'
extra:
  feature:
    tabs: false
  palette:
    primary: 'orange'
    accent: 'orange'
    extra:
  logo: 'img/pipelineio-logo-128x128.png'
  font:
    text: 'Roboto'
    code: 'Source Code Pro'
  social:
    - type: 'github'
      link: 'https://github.com/fluxcapacitor/pipeline'
    - type: 'meetup'
      link: 'https://www.meetup.com/Advanced-Spark-and-TensorFlow-Meetup/'
    - type: 'youtube'
      link: 'https://youtube.com/channel/UCvlZKtekcKkBUuz8f9dhobw'
    - type: 'slideshare'
      link: 'https://www.slideshare.net/cfregly'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/6609122/'
    - type: 'twitter'
      link: 'https://twitter.com/pipelineio'
    - type: 'docker'
      link: 'https://hub.docker.com/r/fluxcapacitor'
      
markdown_extensions:
  - markdown_include.include:
      base_path: docs 
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
extra_css:
  - css/bootstrap_paper.min.css
  - css/style.css
copyright: Copyright &copy; 2017 PipelineIO Inc.
