apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-master
  labels:
    app: mysql-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-master
  template:
    metadata:
      labels:
        app: mysql-master
    spec:
      containers:
      - name: mysql-master
        image: docker.io/fluxcapacitor/sql-mysql
        resources:
          limits:
            cpu: 400m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 150Mi
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 3306
#      nodeSelector:
#        beta.kubernetes.io/instance-type: r3.2xlarge
#        training: "true"
