apiVersion: v1
kind: Service
metadata:
  name: spark-worker-2-1-0
  labels:
    app: spark-worker-2-1-0
#    dns: route53
#  annotations:
#    domainName: "spark-worker.your.domain.com"
spec:
  type: LoadBalancer
  ports:
  - name: admin-http
    port: 80
    targetPort: 6061
  selector:
    app: spark-worker-2-1-0
