apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-5-0-0
  labels:
    app: kibana-5-0-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-5-0-0
  template:
    metadata:
      labels:
        app: kibana-5-0-0
    spec:
      containers:
      - name: kibana-5-0-0
        image: docker.io/fluxcapacitor/kibana-5.0.0:master
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: "Always"
        env:
        ports:
        - containerPort: 5601 
