apiVersion: v1
kind: Service
metadata:
  name: prediction-keyvalue
  labels:
    hystrix.enabled: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: "prometheus"
    prometheus.io/port: "9040"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/prometheus" 
    prometheus.io/port: "9040" 
spec:
  type: LoadBalancer
  ports:
  - name: prediction-keyvalue
    port: 80 
    targetPort: 9040 
  selector:
    name: prediction-keyvalue
    hystrix.enabled: "true" 
