apiVersion: v1
kind: Service
metadata:
  name: prediction-pmml
  labels:
    hystrix.enabled: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/prometheus"
    prometheus.io/port: "80"
spec:
  type: LoadBalancer
  ports:
  - name: prediction-pmml
    port: 80 
    targetPort: 9040 
  selector:
    name: prediction-pmml
    hystrix.enabled: "true" 
