apiVersion: v1
kind: Service
metadata:
  name: prediction-python
  labels:
    app: prediction-python
#      dns: route53
#    annotations:
#      domainName: prediction-python.your.domain.com
spec:
  type: LoadBalancer
  ports:
  - name: http-model-server
    port: 80
    targetPort: 9876
  - name: grpc-tensorflow-serving
    port: 9000
    targetPort: 9000
  selector:    
    app: prediction-python
