apiVersion: v1
kind: Service
metadata:
  name: prediction-tensorflow-1-0
  labels:
    hystrix.enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - name: prediction-tensorflow-1-0
    port: 80 
    targetPort: 9040
  selector:
    name: prediction-tensorflow-1-0
    hystrix.enabled: "true"
