apiVersion: v1
kind: Service
metadata:
  name: prediction-tensorflow
  labels:
    hystrix.enabled: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/prometheus"
    prometheus.io/port: "80"
spec:
  type: LoadBalancer
  ports:
  - name: prediction-tensorflow
    port: 80 
    targetPort: 9040
  selector:
    name: prediction-tensorflow
    hystrix.enabled: "true"
