apiVersion: v1
kind: Service
metadata:
  name: prediction-tensorflow-gpu
  labels:
    app: prediction-tensorflow-gpu
    hystrix.enabled: "true"
#      dns: route53
#    annotations:
#      domainName: prediction-tensorflow-gpu.your.domain.com
spec:
  type: LoadBalancer
  ports:
  - name: prediction-tensorflow-gpu
    port: 80 
    targetPort: 9040
  selector:
    app: prediction-tensorflow-gpu
    hystrix.enabled: "true"
