apiVersion: v1
kind: Service
metadata:
  name: prediction-tensorflow-1-0-gpu
  labels:
    app: prediction-tensorflow-1-0-gpu
    hystrix.enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - name: prediction-tensorflow-1-0-gpu
    port: 80 
    targetPort: 9040
  selector:
    app: prediction-tensorflow-1-0-gpu
    hystrix.enabled: "true"
