apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    hystrix.enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - name: http 
    port: 80 
    targetPort: 9040 
  selector:
    name: api-gateway
    hystrix.enabled: "true"
