apiVersion: v1
kind: ReplicationController
metadata:
  name: loadtest
  labels:
    app: loadtest
spec:
  replicas: 1
  selector:
    name: loadtest
  template:
    metadata:
      labels:
        name: loadtest
    spec:
      containers:
      - name: loadtest 
        image: docker.io/fluxcapacitor/loadtest:v1.2.0
        imagePullPolicy: "Always"
        env:
        - name: TEST_PATHNAMES
          value: /root/tests/RecommendationServiceStressTest-AWS.jmx:/root/tests/RecommendationServiceStressTest-GCP.jmx
      nodeSelector:
        training: "true"
