apiVersion: v1
kind: ReplicationController
metadata:
  name: hdfs-namenode
  labels:
    app: hdfs-namenode
    version: 2.7.2
spec:
  replicas: 1
  selector:
    name: hdfs-namenode
  template:
    metadata:
      labels:
        name: hdfs-namenode
    spec:
      containers:
      - name: hdfs-namenode
        image: docker.io/fluxcapacitor/hdfs-namenode
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 9000
        - containerPort: 50070 
