apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scheduler-airflow
  labels:
    app: scheduler-airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-airflow
  template:
    metadata:
      labels:
        app: scheduler-airflow
    spec:
      containers:
      - name: scheduler-airflow
        image: docker.io/fluxcapacitor/scheduler-airflow:master
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 200Mi
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: SPARK_MASTER
          value: spark://apachespark-master-2-1-0:7077
        - name: SPARK_SUBMIT_ARGS
          value: ""
        ports:
        - containerPort: 8080
        - containerPort: 5000
        - containerPort: 5555
        - containerPort: 8793
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
        securityContext:
          privileged: true
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
