apiVersion: v1
kind: ReplicationController
metadata:
  name: clustered-tensorflow-ps0 
  labels:
    app: clustered-tensorflow-ps0
spec:
  replicas: 1
  selector:
    name: clustered-tensorflow-ps0
  template:
    metadata:
      labels:
        name: clustered-tensorflow-ps0
    spec:
      containers:
      - name: clustered-tensorflow-ps0
        image: docker.io/fluxcapacitor/clustered-tensorflow
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: PS_HOSTS
          value: clustered-tensorflow-ps0:2222,clustered-tensorflow-ps1:2222
        - name: WORKER_HOSTS
          value: clustered-tensorflow-worker0:2222,clustered-tensorflow-worker1:2222
        - name: JOB_NAME
          value: ps
        - name: TASK_INDEX
          value: "0"
        ports:
        - containerPort: 2222
      nodeSelector:
        training: "true"
