site_name: PipelineIO 
site_url: http://www.pipeline.io
site_author: PipelineIO 
repo_url: https://github.com/fluxcapacitor/pipeline/
pages:
    - Home: index.md
    - Get Started:
        - 'Installation': home/install.md
        - 'Getting Started': home/getting_started.md
        - 'Environments': home/environments.md
        - 'PipelineIO Ignore': home/pio_ignore.md
    - Guides:
        - 'Contributing': guides/contributing.md
    - CLI Commands:
        - 'pio': commands/index.md
        - 'pio init-model': commands/init-model.md
        - 'pio deploy': commands/deploy.md
        - 'pio predict': commands/predict.md
    - Legal:
        - 'Privacy': legal/privacy.md
        - 'Terms of Service': legal/terms.md
theme: material
extra:
  palette:
    primary: 'orange'
    accent: 'black'
    extra:
  logo: 'img/pipelineio-logo-128x128.png'
  font:
    text: 'Roboto'
    code: 'Source Code Pro'
  social:
    - type: 'github'
      link: 'https://github.com/fluxcapacitor/pipeline'
    - type: 'twitter'
      link: 'https://twitter.com/pipelineio'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/6609122/'
    - type: 'meetup'
      link: 'https://www.meetup.com/Advanced-Spark-and-TensorFlow-Meetup/'
    - type: 'youtube'
      link: 'https://youtube.com/channel/UCvlZKtekcKkBUuz8f9dhobw'
    - type: 'slideshare'
      link: 'https://www.slideshare.net/cfregly'
      
      
markdown_extensions:
    - markdown_include.include:
        base_path: docs
extra_css:
    - css/bootstrap_paper.min.css
    - css/style.css
copyright: Copyright &copy; 2017 PipelineIO Inc.
