apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zeppelin-master
  labels:
    app: zeppelin-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeppelin-master
  template:
    metadata:
      labels:
        app: zeppelin-master
    spec:
      containers:
      - name: zeppelin
        image: docker.io/fluxcapacitor/zeppelin:zeppelin-0.8.0-SNAPSHOT
        resources:
          limits:
            cpu: 400m
            memory: 1500Mi
          requests:
            cpu: 100m
            memory: 1000Mi
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: SPARK_MASTER
          value: spark://$(SPARK_MASTER_2_1_0_SERVICE_HOST):$(SPARK_MASTER_2_1_0_SERVICE_PORT_SPARK_SUBMIT)
        - name: SPARK_SUBMIT_ARGS
          value: "--conf spark.cores.max=2 --conf spark.executor.memory=2g --packages com.amazonaws:aws-java-sdk:1.7.4,org.apache.hadoop:hadoop-aws:2.7.1,org.apache.spark:spark-streaming-kafka-0-10_2.11:2.0.1 --jars /root/lib/jpmml-sparkml-package-1.0-SNAPSHOT.jar --py-files /root/lib/jpmml.py"
        ports:
        - containerPort: 3123
        - containerPort: 3124
        volumeMounts:
          - name: kube-config-secret-volume
            readOnly: true
            mountPath: /root/.kube
          - name: hadoop-conf-dev-volume
            mountPath: /etc/hadoop/conf
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: kube-config-secret-volume
          secret:
            secretName: kube-config-secret
        - name: hadoop-conf-dev-volume
          secret:
            secretName: hadoop-conf-dev
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor//source.ml"
            revision: "master"
      imagePullSecrets:
        - name: githubsshkey
#      nodeSelector:
#        training: "true"
